Overrides
LifeSG/web-frontend-engine pull request #108
Opened 2023-07-12 02:49 UTC by weili-govtech

**Changes**
- Merging to long-lived branch as part of a 2-part PR
  - part 1: implementation + basic story and unit tests
  - part 2: Stories and unit tests
- Introduced `overrides` key
- Created form schema context as a mean to share schema with the rest of the fields
- Updated `wrapper` to combine the original schema with overrides
  - via `lodash.merge`
- Delete branch

**Changelog entry**

-   New `overrides` key dedicated to update form schema

2023-07-13 07:07 UTC, qroll requested changes

2023-07-14 05:42 UTC, weili-govtech commented on src/stories/2-frontend-engine/frontend-engine.stories.tsx
> +				"Changes the schema by applying on top of it, this can be done on-the-fly and is declared outside `sections`",
ok updated

2023-07-14 05:43 UTC, weili-govtech commented on src/stories/2-frontend-engine/frontend-engine.stories.tsx
> +					summary: "{}",
yup have included

2023-07-14 05:43 UTC, weili-govtech commented on src/utils/object-helper.ts
oops the tests were in another branch, I have just included it in this PR

2023-07-14 06:06 UTC, weili-govtech commented on src/utils/object-helper.ts
> +					return getNestedValueByKey(value as Record<string, T>, key);
ok updated
- prevent returning if there are no matching keys
- pass `options` along in recursive calls excluding `skipRoot=true`

2023-07-14 10:04 UTC, weili-govtech commented on src/utils/object-helper.ts
> +					return getNestedValueByKey(value as Record<string, T>, key);
have further updated it to not return if there are no matches

2023-07-18 01:49 UTC, qroll approved these changes

2023-07-18 01:50 UTC, merged