Date range validation
LifeSG/web-frontend-engine pull request #174
Opened 2023-11-03 09:45 UTC by weili-govtech

**Changes**
- add `notFuture` and `notPast` validation to date range field

2023-11-08 15:46 UTC, qroll requested changes

2023-11-08 15:46 UTC, qroll commented on src/stories/3-fields/date-range-field/date-range-field.stories.tsx
> +NotFutureDate.args = {
minor issue, the story is not showing up properly
```suggestion
NotPastDate.args = {
```

2023-11-09 00:33 UTC, qroll commented
side note we have an outstanding PR for the validation-schema-generator [here](https://github.com/LifeSG/validation-schema-generator/pull/31) (💀) , the enhancements here will need to be ported over as well

2023-11-09 01:05 UTC, weili-govtech commented
whoops I dont know how I missed that PR, I will review it and add on to the validation in another PR

2023-11-09 05:43 UTC, qroll approved these changes

2023-11-09 05:43 UTC, merged