[RBS-952] Nested multi-select component (WIP)
LifeSG/web-frontend-engine pull request #193
Opened 2023-12-06 03:25 UTC by Mono143

**Changes**
- Added a new component, nested multi-select.
- Added relevant tests and stories

-   [keep] branch

**Changelog entry**

-  Added new nested multi-select component

**Additional information**

-   You may refer to [RBS-952](https://jira.ship.gov.sg/browse/RBS-952)
-   Awaiting bugfixes in DS

2023-12-06 08:58 UTC, weili-govtech requested changes

2023-12-06 08:58 UTC, weili-govtech commented on src/components/fields/nested-multi-select/nested-multi-select.tsx
> +		...otherProps
we recently made some enhancements to the label, now all fields are injected with the `formattedLabel` prop, may I trouble you to add it as well, you can refer to: https://github.com/LifeSG/web-frontend-engine/blob/main/src/components/fields/text-field/text-field.tsx#L17

2023-12-14 01:04 UTC, qroll commented
could I trouble you to rebase your changes on top of master instead? GitHub diff doesn't work well with merge commits

2023-12-19 18:53 UTC, Mono143 commented
one thing to note: in the schema tests i noticed that adding a key to the overridden/updated options will cause the test to fail with a TypeError of `Cannot destructure property 'label' of 's' as it is undefined.` 
Can't seem to figure out why this happens. Aside from that everything is ready for review

2023-12-20 16:00 UTC, qroll requested changes

2023-12-20 16:01 UTC, qroll commented
when testing overrides, I noticed that the DS component throws an error when the selected key path doesn't match any option. will be raising a PR to fix this

2023-12-27 07:53 UTC, merged