Create TextBody and Alert components
LifeSG/web-frontend-engine pull request #23
Opened 2022-12-20 10:23 UTC by jeraldlyh

- Created `TextBody` component alongside with its corresponding storybook and unit tests (MOL-11908)
- Created `Alert` component alongside with its corresponding storybook and unit tests (MOL-11907)
- Add import for `FrontendEngineElements` to allow `Wrapper` component to render respective elements
- Shift `Wrapper` component from Field to Element
- Create generic interfaces to reduce boilerplate code
- Rename interface to distinguish between `Field` and `Element` schemas

2022-12-21 02:00 UTC, weili-govtech requested changes

2022-12-21 02:00 UTC, weili-govtech commented on src/stories/4-elements/alert/alert.stories.tsx
> +		...CommonFieldStoryProps("alert", true),
even though we are directing devs to follow the documentation in the design system, we still want to list the props of interest and showcase notable features for easy reference, this also helps prevent disparity in the event of an update on the design system

in this case, we want to showcase the various `type` and the `actionLink`

2022-12-21 02:00 UTC, weili-govtech commented on src/components/elements/alert/alert.tsx
> +	return <DSAlert id={id} data-testid={TestHelper.generateId(id, "alert")} {...schema} />;
is it possible to parse HTML from string? we will want to serve HTML text from JSON

2022-12-21 02:00 UTC, weili-govtech commented on src/components/elements/text-body/text-body.tsx
> +		return typeof children !== "string";
should check if children is an array or object and keys / length > 1

2022-12-21 02:00 UTC, weili-govtech commented on src/stories/4-elements/text-body/text-body.stories.tsx
> +		...CommonFieldStoryProps("textbody", true),
similar to alert, we should list the notable props

2022-12-21 02:04 UTC, weili-govtech commented on src/components/elements/text-body/text-body.tsx
> +	const renderTextBody = (): JSX.Element[] | string[] | string => {
is it possible to parse HTML from string? we will want to serve HTML text from JSON

2023-01-03 08:57 UTC, jeraldlyh commented
Created a wrapper class for `Text` components in another branch

2023-01-05 01:40 UTC, weili-govtech requested changes

2023-01-05 09:37 UTC, weili-govtech approved these changes

2023-01-05 09:37 UTC, merged