[DATEVAL][WL] fix date validation with different date format
LifeSG/web-frontend-engine pull request #37
Opened 2023-03-09 01:23 UTC by weili-govtech

- MOL-12425
- parse date with correct date formatter in validators
- add tests to cover this scenario

2023-03-09 08:07 UTC, qroll requested changes
- the value passed to and from `Form.DateInput` should also be formatted since that is in YYYY-MM-DD
- I think `"is-date"` should also check the format to show the correct error message

2023-03-13 02:58 UTC, weili-govtech commented on src/components/fields/date-input/date-input.tsx
> +					return localDate.isAfter(LocalDate.now());
added optional chaining for this

2023-03-13 03:00 UTC, weili-govtech commented
- updated local state to always use the default `uuuu-MM-dd` date format so it is compatible with `Form.DateInput`
- created new test suite to cover various behaviours with custom date formats

2023-03-15 10:22 UTC, qroll approved these changes

2023-03-15 10:22 UTC, merged