[MOL-12691] Update padding for chips/pills
LifeSG/web-frontend-engine pull request #89
Opened 2023-06-20 09:22 UTC by Hilman-Azfar

Update the padding for chip as advised from ux
-  delete branch

2023-06-20 10:33 UTC, weili-govtech commented on src/components/fields/textarea/textarea.styles.tsx
> +	margin: 0.5rem 0rem 1rem 0rem;
```suggestion
	margin: 0.5rem 0 1rem;
```

2023-06-20 10:38 UTC, weili-govtech commented
does this change affect the `chips` component as well?
https://designsystem.life.gov.sg/web-frontend-engine/index.html?path=/story/field-chips--default

the chips component can come with the textarea too: https://designsystem.life.gov.sg/web-frontend-engine/index.html?path=/story/field-chips--with-textarea

2023-06-21 06:57 UTC, Hilman-Azfar commented
the chips component is unaffected

2023-06-21 08:43 UTC, weili-govtech requested changes

2023-06-21 08:43 UTC, weili-govtech commented on src/components/fields/chips/chips.styles.tsx
> +export const ChipContainer = styled.div<{ showTextarea?: boolean | undefined }>`
rename as `$showTextarea` to mark it as a transient prop

2023-06-21 08:43 UTC, weili-govtech commented on src/components/fields/textarea/textarea.styles.tsx
> +export const ChipContainer = styled.div<{ chipPosition?: "top" | "bottom" | undefined }>`
rename as `$chipPosition` to mark it as a transient prop

2023-06-22 03:25 UTC, weili-govtech approved these changes

2023-06-22 03:25 UTC, merged